# Generated by Django 5.1.2 on 2024-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driving_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания поездки'),
        ),
    ]
